name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch:

jobs:
  ping-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Push Empty Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit --allow-empty -m "Chore: Automated ping to keep Streamlit active"
          git push origin main
